# coding: utf-8

"""
    QEDIT - Asset Transfers

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.6.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pyqedit
from pyqedit.models.create_rule_request import CreateRuleRequest  # noqa: E501
from pyqedit.rest import ApiException


class TestCreateRuleRequest(unittest.TestCase):
    """CreateRuleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateRuleRequest(self):
        """Test CreateRuleRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyqedit.models.create_rule_request.CreateRuleRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
