# coding: utf-8

"""
    QEDIT - Asset Transfers

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.6.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pyqedit
from pyqedit.models.balance_for_asset import BalanceForAsset  # noqa: E501
from pyqedit.rest import ApiException


class TestBalanceForAsset(unittest.TestCase):
    """BalanceForAsset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBalanceForAsset(self):
        """Test BalanceForAsset"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyqedit.models.balance_for_asset.BalanceForAsset()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
