# coding: utf-8

"""
    QEDIT - Asset Transfers

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.6.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import asset_transfer
from asset_transfer.models.get_tasks_response import GetTasksResponse  # noqa: E501
from asset_transfer.rest import ApiException


class TestGetTasksResponse(unittest.TestCase):
    """GetTasksResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTasksResponse(self):
        """Test GetTasksResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = asset_transfer.models.get_tasks_response.GetTasksResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
