# coding: utf-8

"""
    QEDIT - Asset Transfers

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.6.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pyqedit
from pyqedit.models.async_task_created_response import AsyncTaskCreatedResponse  # noqa: E501
from pyqedit.rest import ApiException


class TestAsyncTaskCreatedResponse(unittest.TestCase):
    """AsyncTaskCreatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAsyncTaskCreatedResponse(self):
        """Test AsyncTaskCreatedResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyqedit.models.async_task_created_response.AsyncTaskCreatedResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
