# coding: utf-8

"""
    QEDIT - Asset Transfers

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.6.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pyqedit
from pyqedit.models.get_new_address_response import GetNewAddressResponse  # noqa: E501
from pyqedit.rest import ApiException


class TestGetNewAddressResponse(unittest.TestCase):
    """GetNewAddressResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetNewAddressResponse(self):
        """Test GetNewAddressResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyqedit.models.get_new_address_response.GetNewAddressResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
