# coding: utf-8

"""
    QEDIT - Asset Transfers

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.6.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pyqedit
from pyqedit.models.analytic_issue_wallet_tx import AnalyticIssueWalletTx  # noqa: E501
from pyqedit.rest import ApiException


class TestAnalyticIssueWalletTx(unittest.TestCase):
    """AnalyticIssueWalletTx unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnalyticIssueWalletTx(self):
        """Test AnalyticIssueWalletTx"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyqedit.models.analytic_issue_wallet_tx.AnalyticIssueWalletTx()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
