# coding: utf-8

"""
    QEDIT - Asset Transfers

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.6.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import asset_transfer
from asset_transfer.models.analytic_transaction import AnalyticTransaction  # noqa: E501
from asset_transfer.rest import ApiException


class TestAnalyticTransaction(unittest.TestCase):
    """AnalyticTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnalyticTransaction(self):
        """Test AnalyticTransaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = asset_transfer.models.analytic_transaction.AnalyticTransaction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
