# coding: utf-8

"""
    QEDIT - Asset Transfers

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.6.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pyqedit
from pyqedit.models.import_wallet_request import ImportWalletRequest  # noqa: E501
from pyqedit.rest import ApiException


class TestImportWalletRequest(unittest.TestCase):
    """ImportWalletRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImportWalletRequest(self):
        """Test ImportWalletRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyqedit.models.import_wallet_request.ImportWalletRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
