# coding: utf-8

"""
    QEDIT - Asset Transfers

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.6.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pyqedit
from pyqedit.models.get_wallet_activity_request import GetWalletActivityRequest  # noqa: E501
from pyqedit.rest import ApiException


class TestGetWalletActivityRequest(unittest.TestCase):
    """GetWalletActivityRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetWalletActivityRequest(self):
        """Test GetWalletActivityRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyqedit.models.get_wallet_activity_request.GetWalletActivityRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
