# coding: utf-8

"""
    QEDIT - Asset Transfers

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.6.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pyqedit
from pyqedit.models.rule import Rule  # noqa: E501
from pyqedit.rest import ApiException


class TestRule(unittest.TestCase):
    """Rule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRule(self):
        """Test Rule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyqedit.models.rule.Rule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
