# coding: utf-8

"""
    QEDIT - Asset Transfers

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.6.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import asset_transfer
from asset_transfer.models.export_wallet_request import ExportWalletRequest  # noqa: E501
from asset_transfer.rest import ApiException


class TestExportWalletRequest(unittest.TestCase):
    """ExportWalletRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExportWalletRequest(self):
        """Test ExportWalletRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = asset_transfer.models.export_wallet_request.ExportWalletRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
