# coding: utf-8

"""
    QEDIT - Asset Transfers

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.6.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import asset_transfer
from asset_transfer.models.analytic_rule_wallet_tx import AnalyticRuleWalletTx  # noqa: E501
from asset_transfer.rest import ApiException


class TestAnalyticRuleWalletTx(unittest.TestCase):
    """AnalyticRuleWalletTx unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnalyticRuleWalletTx(self):
        """Test AnalyticRuleWalletTx"""
        # FIXME: construct object with mandatory attributes with example values
        # model = asset_transfer.models.analytic_rule_wallet_tx.AnalyticRuleWalletTx()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
