# coding: utf-8

"""
    QEDIT - Asset Transfers

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.6.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import asset_transfer
from asset_transfer.models.unlock_wallet_request import UnlockWalletRequest  # noqa: E501
from asset_transfer.rest import ApiException


class TestUnlockWalletRequest(unittest.TestCase):
    """UnlockWalletRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnlockWalletRequest(self):
        """Test UnlockWalletRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = asset_transfer.models.unlock_wallet_request.UnlockWalletRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
